version: '3.4'

services:
  blockchainclient:
    image: ${DOCKER_REGISTRY-}blockchainclient
    build:
      context: .
      dockerfile: BlockChainClient/Dockerfile

  blockchainclientSQLdb:
    container_name: blockchainclientSQLdb
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1727:1433"
    environment: 
      - SA_PASSWORD=ForzaInterSempre69!
      - ACCEPT_EULA=Y

  blockchainapi:
    image: ${DOCKER_REGISTRY-}blockchainapi
    build:
      context: .
      dockerfile: BlockChainAPI/Dockerfile
    ports: 
      - "5555:80"
