version: '3.4'

services:
  blockchain-sqldb:
    container_name: blockchain-sqldb
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - 1727:1433
    environment: 
      - SA_PASSWORD=ForzaInterSempre69!
      - ACCEPT_EULA=Y

  blockchain-api:
    container_name: blockchain-api  
    image: blockchain-api-2021:latest    
    build:
      context: .
      dockerfile: BlockChainAPI/Dockerfile
    ports:
      - 5555:80

  blockchain-client:
    image: blockchain-client-2021:latest
    container_name: blockchain-client
    build:
      context: .
      dockerfile: BlockChainClient/Dockerfile
    depends_on:
        - blockchain-sqldb
        - blockchain-api